; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

#https://github.com/platformio/platform-espressif32/pull/921
[env:esp32-s3-devkitc-1]
platform = espressif32 @ ^6.9.0      ; <--- FORCES ESP-IDF 5.1+ / Arduino Core 3.x
framework = arduino
board = esp32-s3-devkitc-1

# Configure options for the N16R8V variant
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

monitor_speed = 115200

lib_deps =
    https://github.com/tzapu/WiFiManager.git
    ArduinoOTA
    https://github.com/buelowp/sunset.git
    https://github.com/sh123/esp32_opus_arduino.git
    https://github.com/tfeldmann/Arduino-Blinkenlight.git

# Configure options for the N16R8V variant
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    ;-DFORCE_DEBUG_MODE
    ; Uncomment and set these to skip the captive portal and connect directly:
    ; -DWIFI_SSID=\"YourNetworkName\"
    ; -DWIFI_PASSWORD=\"YourPassword\"

upload_protocol = espota
upload_port = 10.0.0.12   ; Replace with your device's actual IP
upload_flags =
    --port=3232               ; Optional: Specify the port (default is 3232)